### ISSUE TITLE
Relationships are not commited, but return no error

### ISSUE THREAD

**Issue by pavlot** [mrevutskyi/flask-restless-ng#1] opened 2020-07-20 08:11 UTC
This commented out code makes that relationships are not commited

https://github.com/mrevutskyi/flask-restless-ng/blob/3edf5de504dd0cb45fd049ee9e7430f9a84b8c77/flask_restless/views/relationships.py#L178

I suspect idea was done to allow postprocessors can rollback changes, but now it makes that relationship is not saved.

Also I think that tests should be improved to check not only return status, but try to reload relationship and check whether it exists. Now code return HTTP-204, but it do nothing

**Comment by mrevutskyi** [comment] 2020-11-02 20:08
Closing the issue as I'm not able to reproduce, please reopen if you are still facing it

**Closed by mrevutskyi** 2020-11-02 20:08 UTC
